### ISSUE TITLE
0.5.0 issue

### ISSUE THREAD

**Issue by kamichal** [PyCQA/flake8-commas#48]
After upgrading to version 0.5.0 I got such an error:

```
Traceback (most recent call last):
  File "/obscured_path/flake8", line 11, in <module>
    sys.exit(main())
  File "/obscured_path/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/obscured_path/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/obscured_path/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/obscured_path/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/obscured_path/flake8/checker.py", line 319, in run
    self.run_parallel()
  File "/obscured_path/flake8/checker.py", line 288, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 287, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
KeyError: <object object at 0x7f0fa110d380>
```

It's ran in python 2.7.13 at tox environment (so is pretty clean):
```
asn1crypto==0.24.0
bcrypt==3.1.4
cffi==1.11.2
check-manifest==0.36
clang==3.8
configparser==3.5.0
cryptography==2.1.4
docutils==0.14
enum34==1.1.6
Fabric==1.14.0
flake8==3.5.0
flake8-commas==0.5.0
functools32==3.2.3.post2
idna==2.6
ipaddress==1.0.19
jsonschema==2.5.1
mccabe==0.6.1
packaging==16.8
paramiko==2.4.0
ply==3.10
prophy==1.1.1
pyasn1==0.4.2
pycodestyle==2.3.1
pycparser==2.18
pyflakes==1.6.0
PyNaCl==1.2.1
pyparsing==2.2.0
requests==2.4.3
six==1.11.0
```
Flake version:
```
$ flake8 --version
3.5.0 (flake8_commas._base: 0.5.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.9 on Linux
$ uname -a
Linux dtn 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u5~bpo8+1 (2017-09-28) x86_64 GNU/Linux
```

**Comment by graingert** [comment]
Have you tried 0.5.1?

**Comment by graingert** [comment]
Do you have an example input?

**Comment by graingert** [comment]
@kamichal closing until you post an example.
